/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    // Dashboard background gradients - light mode
    'bg-gradient-to-br',
    'from-purple-200',
    'from-cyan-200', 
    'from-emerald-200',
    'from-rose-200',
    'from-orange-200',
    'from-teal-200',
    'from-slate-200',
    'via-indigo-100',
    'via-sky-100',
    'via-teal-100', 
    'via-pink-100',
    'via-red-100',
    'via-gray-100',
    'to-violet-200',
    'to-blue-200',
    'to-green-200',
    'to-pink-200',
    'to-red-200',
    'to-slate-200',
    
    // Dashboard background gradients - dark mode
    'dark:from-slate-900',
    'dark:via-purple-900',
    'dark:via-cyan-900',
    'dark:via-emerald-900', 
    'dark:via-rose-900',
    'dark:via-red-900',
    'dark:via-blue-900',
    'dark:via-slate-800',
    'dark:to-violet-900',
    'dark:to-sky-900',
    'dark:to-teal-900',
    'dark:to-pink-900',
    'dark:to-orange-900',
    'dark:to-indigo-900',
    'dark:to-gray-900',
    
    // Dashboard blur gradients
    'bg-gradient-to-r',
    'from-indigo-500/35',
    'from-blue-500/35',
    'from-green-500/35',
    'from-pink-500/35',
    'from-orange-500/35',
    'from-teal-500/35',
    'from-slate-500/35',
    'via-purple-500/40',
    'via-cyan-500/40',
    'via-emerald-500/40',
    'via-rose-500/40',
    'via-red-500/40',
    'via-blue-500/40',
    'via-gray-500/40',
    'to-rose-500/35',
    'to-teal-500/35',
    'to-pink-500/35',
    'to-orange-500/35',
    'to-indigo-500/35',
    'to-slate-500/35',
    
    // Additional theme colors that might be used dynamically
    'bg-indigo-600',
    'bg-blue-600',
    'bg-green-600',
    'bg-pink-600',
    'bg-orange-600',
    'bg-teal-700',
    'bg-slate-700',
    'dark:bg-indigo-500',
    'dark:bg-blue-500',
    'dark:bg-green-500',
    'dark:bg-pink-500',
    'dark:bg-orange-500',
    'dark:bg-teal-600',
    'dark:bg-slate-600',
    
    // Button gradients that might be used
    'bg-gradient-to-br',
    'from-indigo-600',
    'from-blue-600',
    'from-green-600',
    'from-pink-600',
    'from-orange-600',
    'from-teal-700',
    'from-slate-700',
    'to-purple-700',
    'to-cyan-500',
    'to-emerald-600',
    'to-rose-600',
    'to-red-600',
    'to-blue-800',
    'to-slate-800',
    'via-indigo-700',
    'via-blue-700',
    'via-green-700',
    'via-pink-700',
    'via-orange-700',
    'via-teal-800',
    'via-slate-800',
    
    // Text colors
    'text-indigo-600',
    'text-blue-600',
    'text-green-600',
    'text-pink-600',
    'text-orange-600',
    'text-teal-700',
    'text-slate-700',
    'dark:text-indigo-400',
    'dark:text-blue-400',
    'dark:text-green-400',
    'dark:text-pink-400',
    'dark:text-orange-400',
    'dark:text-teal-300',
    'dark:text-slate-300',
    
    // Shadow colors
    'shadow-indigo-500/25',
    'shadow-blue-500/25',
    'shadow-green-500/25',
    'shadow-pink-500/25',
    'shadow-orange-500/25',
    'shadow-teal-500/25',
    'shadow-slate-500/25',

    'hover:shadow-indigo-500/25',
    'hover:shadow-indigo-500/20',
    'hover:shadow-blue-500/25', 
    'hover:shadow-blue-500/20',
    'hover:shadow-green-500/25',
    'hover:shadow-green-500/20',
    'hover:shadow-pink-500/25',
    'hover:shadow-pink-500/20',
    'hover:shadow-orange-500/25',
    'hover:shadow-orange-500/20',
    'hover:shadow-teal-500/25',
    'hover:shadow-teal-500/20',
    'hover:shadow-slate-500/25',
    'hover:shadow-slate-500/20',
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}